[package]
name = "aleowrap"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aleowrap"

[dependencies]
rayon = "1.8.0"
serde = "1.0"
serde_json = "1.0"
aleo-std = "1.0.1"

[dependencies.ahash]
version = "0.8.8"

[dependencies.snarkvm-console]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.snarkvm-circuit]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.snarkvm-synthesizer]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.snarkvm-ledger-block]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.snarkvm-ledger-query]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"
features = ["async"]

[dependencies.snarkvm-ledger-store]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.snarkvm-utilities]
git = "https://github.com/ProvableHQ/snarkVM.git"
branch = "testnet"

[dependencies.anyhow]
version = "1.0.75"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.ureq]
version = "3"

[dependencies.time]
version = "0.3.36"
features = ["macros"]

[dependencies.tracing]
version = "0.1"

[dependencies.js-sys]
version = "0.3"

[dependencies.tracing-subscriber]
version = "0.3.19"
features = [ "env-filter", "parking_lot", "time", "local-time" ]

[features]
default = []
mainnet = []
testnetv0 = []